const EventActions = {
  JOIN_EVENT_START: "JOIN_EVENT_START",
  JOIN_EVENT_SUCCESS: "JOIN_EVENT_SUCCESS",
  JOIN_EVENT_DENY: "JOIN_EVENT_DENY",
  JOIN_EVENT_FAILURE: "JOIN_EVENT_FAILURE",

  EXIST_EVENT_START: "EXIST_EVENT_START",
  EXIST_EVENT_SUCCESS: "EXIST_EVENT_SUCCESS",
  EXIST_EVENT_NOT_EXIST: "EXIST_EVENT_NOT_EXIST",
  EXIST_EVENT_FAILURE: "EXIST_EVENT_FAILURE",

  VOTE_EVENT_START: "VOTE_EVENT_START",
  VOTE_EVENT_SUCCESS: "VOTE_EVENT_SUCCESS",
  VOTE_EVENT_FAILURE: "VOTE_EVENT_FAILURE",

  UPDATE_DATA_EVENT: "UPDATE_DATA_EVENT",
  UPDATE_RESULTS_EVENT: "UPDATE_RESULTS_EVENT",
}

export default EventActions
